services:
  telegram-monitor:
    build: .
    container_name: telegram-monitor
    restart: always
    env_file:
      - .env
    volumes:
      - ./log:/app/log
      - ./current_ip.json:/app/current_ip.json